'''' Dict of PSS attributes '''

pss_attr = {'Encoder Index': 0,
            'Void': 1,
            'Shot ID': 2,
            'File Num': 3,
            'EP ID': 4,
            'Line': 5,
            'Station': 6,
            'Date': 7,
            'Time': 8,
            'Comment': 9,
            'TB Date': 10,
            'TB Time': 11,
            'TB Micro': 12,
            'Record Index': 13,
            'EP Count': 14,
            'Crew ID': 15,
            'Unit ID': 16,
            'Start Code': 17,
            'Sweep Checksum': 18,
            'Param Checksum': 19,
            'Phase Max': 20,
            'Phase Avg': 21,
            'Force Max': 22,
            'Force Avg': 23,
            'THD Max': 24,
            'THD Avg': 25,
            'Force Out': 26,
            'GPS Time': 27,
            'Lat': 28,
            'Lon': 29,
            'Altitude': 30,
            'GPS Altitude': 31,
            'Sats': 32,
            'PDOP': 33,
            'HDOP': 34,
            'VDOP': 35,
            'Age': 36,
            'Quality': 37,
            'Start Time Delta': 38,
            'Sweep Number': 39,
            'Signature File Number': 40,
            'Flash Storage Free Spac': 41,
            'Flash Storage Status': 42,
            'USB Storage Status': 43,
            'Vibrator QC': 44,
            'Encoder ID': 45,
            'Encoder IP': 46,
            'Max Viscosity': 47,
            'Min Viscosity': 48,
            'Avg Viscosity': 49,
            'Max Stiffness': 50,
            'Min Stiffness': 51,
            'Avg Stiffness': 52,
            'Target Force': 53,
            'Bearing': 54,          # not consistent
           }

